version: '3.6'

services:

  front:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/front:${CI_COMMIT_SHORT_SHA}
    container_name: front
    restart: unless-stopped
    ports:
      - 80:80